apiVersion: v1
kind: Pod
metadata:
  name: phppot-mysql
  namespace: staging
  labels:
    app: mariadb
spec:
  containers:
  - name: mariadb
    image: mariadb
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: sqlpass
---
apiVersion: v1
kind: Service
metadata:
  name: event-mysql
  namespace: staging
  labels:
    app: mariadb
spec:
  type: ClusterIP
  ports:
    - name: event-backend
      port: 3306
      targetPort: 3306
  selector:
    app: mariadb
