apiVersion: apps/v1
kind: Deployment
metadata:
  name: phppot-event
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-frontend
  template:
    metadata:
      labels:
        app: event-frontend
    spec:
      containers:
      - name: event-php
        #        imagePullPolicy: Never
        image: anooprs471/phppot-event
        ports:
          - name: httpport
            containerPort: 80
        envFrom:
          - configMapRef:
              name: event-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: event-web
  namespace: staging
  labels:
    app: event-frontend
spec:
  type: NodePort
  ports:
    - name: event-frontend
      nodePort: 30163
      port: 80
      targetPort: 80
  selector:
    app: event-frontend
